{
 "title": "UDPSmoke",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(udpsmoke_sent,instance)"
    }
   },
   {
    "name": "target",
    "label": "target",
    "query": {
     "query": "label_values(udpsmoke_lost,peer)"
    }
   },
   {
    "name": "proto",
    "label": "proto",
    "query": {
     "query": "label_values(udpsmoke_lost,proto)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Delivered pkts (%, 1h avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100*rate(udpsmoke_received{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[1h])/rate(udpsmoke_sent{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[1h])"
    }
   ]
  },
  {
   "title": "Loss (%, 30s avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100*rate(udpsmoke_lost{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[30s])/rate(udpsmoke_sent{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[30s])"
    }
   ]
  },
  {
   "title": "Loss (abs pkts/30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(udpsmoke_lost{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[30s])"
    }
   ]
  },
  {
   "title": "Loss (%, 1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100*rate(udpsmoke_lost{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[1m])/rate(udpsmoke_sent{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[1m])"
    }
   ]
  },
  {
   "title": "RTT (ms, 1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(udpsmoke_rtt_sum{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[1m])/rate(udpsmoke_rtt_count{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[1m])"
    }
   ]
  },
  {
   "title": "Out-of-order (pkts/1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "60*rate(udpsmoke_outoforder{instance=~\"$instance\",peer=~\"$target\",proto=~\"$proto\"}[1m])"
    }
   ]
  }
 ]
}